import { useCallback, useEffect, useRef, useState, type DragEvent } from "react";
import { Background, Controls, Handle, MiniMap, Position, ReactFlow, addEdge, applyEdgeChanges, applyNodeChanges, type Connection, type Edge, type EdgeChange, type Node, type NodeChange, type NodeProps, type ReactFlowInstance } from "@xyflow/react";
import { AudioLines, Captions, Check, CheckCircle2, CircleAlert, CircleX, Clipboard, Cpu, Crop, FilePlus2, FileVideo, Gauge, GitBranch, ListPlus, MousePointer2, Palette, PanelRight, Percent, Play, Plus, Puzzle, Redo2, Replace, RotateCw, Save, Scaling, ScanLine, Search, Settings2, ShieldCheck, SlidersHorizontal, Tags, Terminal, TestTube2, Trash2, Undo2, Video, WandSparkles, Waves, Workflow, X, type LucideIcon } from "lucide-react";
import { validateFlow } from "@flowarr/flow-engine";
import type { FlowGraph, FlowNode, FlowNodeKind, MediaFile } from "@flowarr/shared";
import { api } from "../api";
import { PageError } from "./Dashboard";

type Summary = { id: string; name: string; revision: number; updatedAt: string };
const labels: Record<FlowNodeKind, string> = {
  input: "File input", "probe-media": "Probe media",
  "codec-check": "Video codec?", "bit-depth-check": "Bit depth?", "hdr-check": "HDR?", "resolution-check": "Resolution?", subflow: "Call subflow", "plugin-node": "Plugin block",
  "ffmpeg-start": "FFmpeg plan", "hevc-encode": "Encode HEVC", "video-encode": "Encode video", scale: "Resize video", "pixel-format": "Pixel format",
  "frame-rate": "Frame rate", crop: "Crop video", rotate: "Rotate & flip", deinterlace: "Deinterlace",
  "audio-encode": "Encode audio", "audio-normalize": "Normalize loudness", "subtitle-mode": "Subtitles", "metadata-mode": "Metadata",
  "custom-args": "Custom arguments", "custom-ffmpeg": "Custom FFmpeg command", "ffmpeg-execute": "Execute",
  validate: "Validate output", "minimum-saving": "Minimum saving", replace: "Replace original", success: "Finish", failure: "Fail job"
};
const catalog: Array<{ category: string; items: FlowNodeKind[] }> = [
  { category: "Input", items: ["input", "probe-media"] },
  { category: "Logic", items: ["codec-check", "bit-depth-check", "hdr-check", "resolution-check", "subflow"] },
  { category: "Video", items: ["video-encode", "scale", "pixel-format", "frame-rate", "crop", "rotate", "deinterlace"] },
  { category: "Audio & streams", items: ["audio-encode", "audio-normalize", "subtitle-mode", "metadata-mode"] },
  { category: "FFmpeg", items: ["ffmpeg-start", "custom-args", "custom-ffmpeg", "ffmpeg-execute"] },
  { category: "Output", items: ["validate", "minimum-saving", "replace", "success", "failure"] }
];
const icons: Record<FlowNodeKind, LucideIcon> = {
  input: FileVideo, "probe-media": ScanLine,
  "codec-check": GitBranch, "bit-depth-check": GitBranch, "hdr-check": GitBranch, "resolution-check": GitBranch, subflow: Workflow, "plugin-node": Puzzle,
  "ffmpeg-start": SlidersHorizontal, "hevc-encode": Video, "video-encode": Video, scale: Scaling, "pixel-format": Palette,
  "frame-rate": Gauge, crop: Crop, rotate: RotateCw, deinterlace: ScanLine,
  "audio-encode": AudioLines, "audio-normalize": Waves, "subtitle-mode": Captions, "metadata-mode": Tags, "custom-args": ListPlus, "custom-ffmpeg": Terminal, "ffmpeg-execute": Play,
  validate: ShieldCheck, "minimum-saving": Percent, replace: Replace, success: CheckCircle2, failure: CircleX
};
type StarterTemplate = "blank" | "hevc" | "gpu" | "audio";
type PluginField = { key: string; label: string; type: "string" | "number" | "boolean" | "select"; default?: string | number | boolean; placeholder?: string; min?: number; max?: number; step?: number; options?: Array<{ value: string; label: string }> };
type PluginNodeDefinition = { id: string; label: string; description: string; category?: string; expandsTo: FlowNodeKind; defaults?: Record<string, unknown>; fields?: PluginField[] };
type PluginManifest = { id: string; name: string; version: string; description: string; nodes: PluginNodeDefinition[] };
type PluginCatalog = { plugins: PluginManifest[]; errors: Array<{ file: string; error: string }> };
const starterTemplates: Array<{ id: StarterTemplate; name: string; description: string; icon: LucideIcon }> = [
  { id: "blank", name: "Blank canvas", description: "Start from nothing and build your own route.", icon: FilePlus2 },
  { id: "hevc", name: "H.264 to HEVC", description: "Codec branch, x265 encode, validation and safe replace.", icon: WandSparkles },
  { id: "gpu", name: "GPU HEVC", description: "NVENC starter with copied audio and output validation.", icon: Cpu },
  { id: "audio", name: "AAC audio", description: "Encode audio to AAC while preserving the video stream.", icon: AudioLines }
];
const nodeTypes = { flow: FlowNodeView };
export function Flows() {
  const [list, setList] = useState<Summary[] | null>(null); const [plugins, setPlugins] = useState<PluginCatalog>({ plugins: [], errors: [] }); const [selected, setSelected] = useState<string | null>(null); const [graph, setGraph] = useState<FlowGraph | null>(null); const [revision, setRevision] = useState(0); const [error, setError] = useState(""); const [notice, setNotice] = useState<{ kind: "success" | "error"; text: string } | null>(null); const [templatesOpen, setTemplatesOpen] = useState(false); const [dirty, setDirty] = useState(false); const [deleting, setDeleting] = useState(false); const [past, setPast] = useState<FlowGraph[]>([]); const [future, setFuture] = useState<FlowGraph[]>([]); const [testOpen, setTestOpen] = useState(false);
  const load = useCallback(() => api<Summary[]>("/api/flows").then(setList).catch((e) => setError(e.message)), []); useEffect(() => { void load(); }, [load]);
  useEffect(() => { api<PluginCatalog>("/api/plugins").then(setPlugins).catch((reason) => setPlugins({ plugins: [], errors: [{ file: "Plugin API", error: reason instanceof Error ? reason.message : String(reason) }] })); }, []);
  useEffect(() => { if (!templatesOpen) return; const close = (event: KeyboardEvent) => { if (event.key === "Escape") setTemplatesOpen(false); }; window.addEventListener("keydown", close); return () => window.removeEventListener("keydown", close); }, [templatesOpen]);
  useEffect(() => { if (notice?.kind !== "success") return; const timeout = window.setTimeout(() => setNotice(null), 4000); return () => window.clearTimeout(timeout); }, [notice]);
  const canLeave = () => !dirty || window.confirm("Discard unsaved flow changes?");
  const resetHistory = () => { setPast([]); setFuture([]); };
  const changeGraph = (next: FlowGraph, record = true) => { if (!graph || JSON.stringify(graph) === JSON.stringify(next)) return; if (record) { setPast((items) => [...items.slice(-49), graph]); setFuture([]); } setGraph(next); setDirty(true); };
  const checkpoint = (before: FlowGraph) => { if (!graph || JSON.stringify(before) === JSON.stringify(graph)) return; setPast((items) => [...items.slice(-49), before]); setFuture([]); setDirty(true); };
  const undo = useCallback(() => { const previous = past.at(-1); if (!previous || !graph) return; setPast((items) => items.slice(0, -1)); setFuture((items) => [graph, ...items].slice(0, 50)); setGraph(previous); setDirty(true); setNotice(null); }, [graph, past]);
  const redo = useCallback(() => { const next = future[0]; if (!next || !graph) return; setFuture((items) => items.slice(1)); setPast((items) => [...items.slice(-49), graph]); setGraph(next); setDirty(true); setNotice(null); }, [future, graph]);
  useEffect(() => { const key = (event: KeyboardEvent) => { const target = event.target as HTMLElement | null; if (target?.matches("input, textarea, select, [contenteditable=true]")) return; if (!(event.ctrlKey || event.metaKey)) return; if (event.key.toLowerCase() === "z" && event.shiftKey) { event.preventDefault(); redo(); } else if (event.key.toLowerCase() === "z") { event.preventDefault(); undo(); } else if (event.key.toLowerCase() === "y") { event.preventDefault(); redo(); } }; window.addEventListener("keydown", key); return () => window.removeEventListener("keydown", key); }, [redo, undo]);
  const select = async (id: string, leaveConfirmed = false) => { if (!id || id === selected || (!leaveConfirmed && !canLeave())) return; const result = await api<{ graph: FlowGraph; revision: number }>(`/api/flows/${id}`); setSelected(id); setGraph(result.graph); setRevision(result.revision); setDirty(false); setNotice(null); setTestOpen(false); resetHistory(); };
  const createTemplate = async (template: StarterTemplate) => { if (!canLeave()) return; const result = await api<{ id: string; graph: FlowGraph; revision: number }>(`/api/flows/templates/${template}`, { method: "POST" }); await load(); setSelected(result.id); setGraph(result.graph); setRevision(result.revision); setDirty(false); setTemplatesOpen(false); setTestOpen(false); resetHistory(); setNotice({ kind: "success", text: template === "blank" ? "Blank flow created" : "Template ready to edit" }); };
  const rename = async () => { const name = graph?.name.trim(); if (!graph || !selected) return; if (!name) { const previous = list?.find((item) => item.id === selected)?.name ?? "Untitled flow"; setGraph({ ...graph, name: previous }); setNotice({ kind: "error", text: "Flow name cannot be empty" }); return; } try { const result = await api<{ name: string }>(`/api/flows/${selected}/name`, { method: "PATCH", body: JSON.stringify({ name }) }); setGraph((current) => current ? { ...current, name: result.name } : current); await load(); setNotice({ kind: "success", text: "Flow renamed" }); } catch (e) { setNotice({ kind: "error", text: e instanceof Error ? e.message : String(e) }); } };
  const save = async () => { if (!graph || !selected) return; try { const result = await api<{ revision: number }>(`/api/flows/${selected}`, { method: "PUT", body: JSON.stringify({ graph, comment: "Saved from visual editor" }) }); setRevision(result.revision); setDirty(false); setNotice({ kind: "success", text: "Flow validated and saved" }); await load(); } catch (e) { setNotice({ kind: "error", text: e instanceof Error ? e.message : String(e) }); } };
  const remove = async () => { if (!graph || !selected || deleting) return; const warning = dirty ? " Unsaved changes will also be lost." : ""; if (!window.confirm(`Delete “${graph.name}” permanently?${warning}`)) return; setDeleting(true); try { await api<void>(`/api/flows/${selected}`, { method: "DELETE" }); setList((current) => current?.filter((item) => item.id !== selected) ?? current); setSelected(null); setGraph(null); setRevision(0); setDirty(false); setNotice(null); setTestOpen(false); resetHistory(); } catch (e) { setNotice({ kind: "error", text: e instanceof Error ? e.message : String(e) }); } finally { setDeleting(false); } };
  const validationErrors = graph ? validateFlow(graph) : [];
  if (error) return <PageError message={error} retry={load}/>;
  return <section className="flow-page"><div className="flow-editor-bar"><div className="flow-identity"><span className="flow-mark"><GitBranch size={16}/></span>{graph ? <input className="flow-name" aria-label="Flow name" value={graph.name} maxLength={80} onChange={(event) => setGraph({ ...graph, name: event.target.value })} onBlur={() => void rename()} onKeyDown={(event) => { if (event.key === "Enter") event.currentTarget.blur(); }}/> : <strong>Flow studio</strong>}<span className="revision">rev {revision}{dirty ? " · unsaved" : ""}</span></div><div className="flow-actions"><label className="flow-select"><select aria-label="Select flow" value={selected ?? ""} onChange={(event) => { const next = event.target.value; if (!canLeave()) { event.target.value = selected ?? ""; return; } void select(next, true); }}><option value="" disabled>{list ? "Select a flow" : "Loading…"}</option>{list?.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><button className="secondary" aria-expanded={templatesOpen} aria-controls="flow-template-picker" onClick={() => setTemplatesOpen((open) => !open)}><Plus size={15}/>New flow</button>{graph && <div className="history-actions"><button className="icon" disabled={!past.length} onClick={undo} aria-label="Undo" title="Undo (Ctrl+Z)"><Undo2 size={15}/></button><button className="icon" disabled={!future.length} onClick={redo} aria-label="Redo" title="Redo (Ctrl+Shift+Z)"><Redo2 size={15}/></button></div>}{graph && <button className="secondary test-flow" onClick={() => setTestOpen((open) => !open)} aria-expanded={testOpen}><TestTube2 size={15}/>Test</button>}{graph && <button className="delete-flow" disabled={deleting} onClick={() => void remove()} aria-label={`Delete flow ${graph.name}`}><Trash2 size={15}/><span>{deleting ? "Deleting…" : "Delete"}</span></button>}{graph && <button className="primary" disabled={validationErrors.length > 0} title={validationErrors[0]} onClick={save}><Save size={15}/>Save <span>{validationErrors.length ? `${validationErrors.length} errors` : `revision ${revision + 1}`}</span></button>}</div></div>
    {templatesOpen && <TemplatePicker create={createTemplate} close={() => setTemplatesOpen(false)}/>}
    <div className="flow-stage">{graph ? <><FlowCanvas graph={graph} flows={(list ?? []).filter((flow) => flow.id !== selected)} plugins={plugins} change={changeGraph} checkpoint={checkpoint} notice={notice} dismissNotice={() => setNotice(null)} validationErrors={validationErrors}/>{testOpen && selected && <FlowTestPanel flowId={selected} graph={graph} close={() => setTestOpen(false)}/>}</> : <TemplateWelcome create={createTemplate}/>}</div>
  </section>;
}

type TestResult = { path: Array<{ id: string; kind: FlowNodeKind }>; executes: boolean; command: string[] | null };
function FlowTestPanel({ flowId, graph, close }: { flowId: string; graph: FlowGraph; close: () => void }) {
  const [files, setFiles] = useState<MediaFile[]>([]); const [fileId, setFileId] = useState(""); const [result, setResult] = useState<TestResult | null>(null); const [error, setError] = useState(""); const [running, setRunning] = useState(false);
  useEffect(() => { api<MediaFile[]>("/api/files").then((items) => { const usable = items.filter((item) => item.probe); setFiles(usable); setFileId(usable[0]?.id ?? ""); }).catch((reason) => setError(reason instanceof Error ? reason.message : String(reason))); }, []);
  const run = async () => { if (!fileId) return; setRunning(true); setError(""); setResult(null); try { setResult(await api<TestResult>(`/api/flows/${flowId}/test`, { method: "POST", body: JSON.stringify({ fileId, graph }) })); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } finally { setRunning(false); } };
  const command = result?.command?.map((part, index) => index === 0 ? part : JSON.stringify(part)).join(" ") ?? "";
  return <aside className="flow-test-panel" aria-label="Test flow"><header><div><TestTube2 size={16}/><span><strong>Dry run</strong><small>No file changes</small></span></div><button className="icon" onClick={close} aria-label="Close flow test"><X size={16}/></button></header><div className="flow-test-body"><label>Probed media<select aria-label="Test media file" value={fileId} onChange={(event) => { setFileId(event.target.value); setResult(null); }}><option value="" disabled>{files.length ? "Choose media" : "No probed media found"}</option>{files.map((file) => <option key={file.id} value={file.id}>{file.path.split(/[\\/]/).at(-1)}</option>)}</select></label><button className="primary" disabled={!fileId || running} onClick={() => void run()}><Play size={14}/>{running ? "Testing…" : "Run dry test"}</button>{error && <div className="test-error"><CircleX size={14}/>{error}</div>}{result && <><section><h3>Resolved path</h3><ol>{result.path.map((node) => <li key={node.id}><span>{labels[node.kind]}</span><code>{node.kind}</code></li>)}</ol></section>{result.executes && command ? <section><div className="test-command-title"><h3>FFmpeg command</h3><button className="icon" onClick={() => void navigator.clipboard.writeText(command)} aria-label="Copy FFmpeg command"><Clipboard size={14}/></button></div><pre>{command}</pre></section> : <div className="test-warning"><CircleAlert size={14}/>This path ends without an FFmpeg execute block.</div>}</>}</div></aside>;
}

function TemplatePicker({ create, close }: { create: (template: StarterTemplate) => void; close: () => void }) {
  return <aside id="flow-template-picker" className="template-picker" role="dialog" aria-modal="false" aria-label="Choose a flow template"><header><div><strong>New flow</strong><span>Choose a starting point</span></div><button className="icon" onClick={close} aria-label="Close templates"><X size={16}/></button></header><div>{starterTemplates.map((template) => { const Icon = template.icon; return <button key={template.id} onClick={() => void create(template.id)}><Icon size={18}/><span><strong>{template.name}</strong><small>{template.description}</small></span><Plus size={15}/></button>; })}</div></aside>;
}

function TemplateWelcome({ create }: { create: (template: StarterTemplate) => void }) {
  return <div className="template-welcome"><div className="welcome-copy"><MousePointer2 size={23}/><h1>Build a media flow</h1><p>Pick a tested starter or open a blank canvas. Drag blocks from the right, then wire every path to an outcome.</p></div><div className="template-grid">{starterTemplates.map((template) => { const Icon = template.icon; return <button key={template.id} onClick={() => void create(template.id)}><Icon size={21}/><strong>{template.name}</strong><span>{template.description}</span></button>; })}</div></div>;
}
function FlowCanvas({ graph, flows, plugins, change, checkpoint, notice, dismissNotice, validationErrors }: { graph: FlowGraph; flows: Summary[]; plugins: PluginCatalog; change: (graph: FlowGraph, record?: boolean) => void; checkpoint: (graph: FlowGraph) => void; notice: { kind: "success" | "error"; text: string } | null; dismissNotice: () => void; validationErrors: string[] }) {
  const [instance, setInstance] = useState<ReactFlowInstance | null>(null);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [paletteOpen, setPaletteOpen] = useState(false);
  const dragStart = useRef<FlowGraph | null>(null);
  const invalidIds = new Set(graph.nodes.filter((node) => validationErrors.some((problem) => problem.includes(node.id))).map((node) => node.id));
  const pluginDefinition = (node: FlowNode) => plugins.plugins.find((plugin) => plugin.id === node.config?.pluginId)?.nodes.find((item) => item.id === node.config?.nodeType);
  const nodes: Node[] = graph.nodes.map((node) => ({ id: node.id, type: "flow", position: node.position, selected: node.id === selectedId, width: 176, height: 58, measured: { width: 176, height: 58 }, data: { kind: node.kind, label: node.kind === "subflow" ? flows.find((flow) => flow.id === node.config?.flowId)?.name ?? labels.subflow : node.kind === "plugin-node" ? pluginDefinition(node)?.label ?? labels["plugin-node"] : labels[node.kind], invalid: invalidIds.has(node.id) } }));
  const edges: Edge[] = graph.edges.map((edge) => ({ ...edge, type: "step", label: edge.sourceHandle && edge.sourceHandle !== "default" ? edge.sourceHandle.toUpperCase() : undefined, animated: false, style: { stroke: "#77807a", strokeWidth: 1.4 } }));
  useEffect(() => { if (!instance || !nodes.length) return; const frame = requestAnimationFrame(() => void instance.fitView({ padding: 0.18 })); return () => cancelAnimationFrame(frame); }, [instance, nodes.length]);
  const onNodesChange = (changes: NodeChange[]) => { const updated = applyNodeChanges(changes, nodes); const remaining = new Set(updated.map((item) => item.id)); if (selectedId && !remaining.has(selectedId)) setSelectedId(null); change({ ...graph, nodes: graph.nodes.filter((node) => remaining.has(node.id)).map((node) => ({ ...node, position: updated.find((item) => item.id === node.id)?.position ?? node.position })), edges: graph.edges.filter((edge) => remaining.has(edge.source) && remaining.has(edge.target)) }, !changes.some((item) => item.type === "position")); };
  const onEdgesChange = (changes: EdgeChange[]) => { const updated = applyEdgeChanges(changes, edges); change({ ...graph, edges: updated.map((edge) => ({ id: edge.id, source: edge.source, target: edge.target, sourceHandle: edge.sourceHandle ?? undefined })) }); };
  const onConnect = (connection: Connection) => { const updated = addEdge(connection, edges); change({ ...graph, edges: updated.map((edge) => ({ id: edge.id, source: edge.source, target: edge.target, sourceHandle: edge.sourceHandle ?? undefined })) }); };
  const addBlock = (kind: FlowNodeKind, position?: { x: number; y: number }) => {
    if (kind === "input" && graph.nodes.some((node) => node.kind === "input")) return;
    const defaults = defaultConfig(kind);
    const offset = graph.nodes.length * 24;
    const id = `${kind}-${crypto.randomUUID()}`;
    change({ ...graph, nodes: [...graph.nodes, { id, kind, position: position ?? { x: 120 + offset, y: 120 + offset }, config: defaults }] });
    setSelectedId(id);
  };
  const addPluginBlock = (plugin: PluginManifest, definition: PluginNodeDefinition) => {
    const id = `plugin-node-${crypto.randomUUID()}`; const offset = graph.nodes.length * 24;
    const options = Object.fromEntries((definition.fields ?? []).filter((field) => field.default !== undefined).map((field) => [field.key, field.default]));
    change({ ...graph, nodes: [...graph.nodes, { id, kind: "plugin-node", position: { x: 120 + offset, y: 120 + offset }, config: { pluginId: plugin.id, nodeType: definition.id, options } }] }); setSelectedId(id);
  };
  const onDrop = (event: DragEvent) => { event.preventDefault(); const kind = event.dataTransfer.getData("application/flowarr-node") as FlowNodeKind; if (!labels[kind] || !instance) return; addBlock(kind, instance.screenToFlowPosition({ x: event.clientX, y: event.clientY })); };
  const selectedNode = graph.nodes.find((node) => node.id === selectedId) ?? null;
  const updateConfig = (config: Record<string, unknown>) => change({ ...graph, nodes: graph.nodes.map((node) => node.id === selectedId ? { ...node, config } : node) });
  const removeBlock = (id: string) => { change({ ...graph, nodes: graph.nodes.filter((node) => node.id !== id), edges: graph.edges.filter((edge) => edge.source !== id && edge.target !== id) }); setSelectedId(null); };
  return <><div className="canvas-shell">{notice && <div className={`canvas-notice ${notice.kind}`} role="status" aria-live="polite">{notice.kind === "error" ? <CircleX size={15}/> : <Check size={15}/>}<span>{notice.text}</span><button className="notice-close" onClick={dismissNotice} aria-label="Dismiss notification"><X size={13}/></button></div>}{validationErrors.length > 0 && <div className="flow-validation" role="status"><div><CircleAlert size={16}/><strong>{validationErrors.length} flow {validationErrors.length === 1 ? "error" : "errors"}</strong></div><ul>{validationErrors.slice(0, 4).map((problem) => <li key={problem}>{problem}</li>)}</ul>{validationErrors.length > 4 && <small>+{validationErrors.length - 4} more</small>}</div>}<button className="mobile-palette-toggle" aria-label="Toggle block palette" aria-expanded={paletteOpen} onClick={() => setPaletteOpen((open) => !open)}><PanelRight size={15}/>Blocks</button><ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} onInit={setInstance} onNodeClick={(_event, node) => setSelectedId(node.id)} onNodeDragStart={() => { dragStart.current = graph; }} onNodeDragStop={() => { if (dragStart.current) checkpoint(dragStart.current); dragStart.current = null; }} onPaneClick={() => setSelectedId(null)} onNodesChange={onNodesChange} onEdgesChange={onEdgesChange} onConnect={onConnect} onDrop={onDrop} onDragOver={(event) => { event.preventDefault(); event.dataTransfer.dropEffect = "move"; }} fitView minZoom={0.2} maxZoom={1.8} deleteKeyCode={["Backspace", "Delete"]}><Background color="#303633" gap={28} size={1}/><MiniMap pannable zoomable nodeColor="#20c997" maskColor="rgba(8,11,10,.78)"/><Controls showInteractive={false}/></ReactFlow>{selectedNode && <NodeConfigPanel node={selectedNode} flows={flows} plugins={plugins.plugins} update={updateConfig} remove={() => removeBlock(selectedNode.id)} close={() => setSelectedId(null)}/>}</div><NodePalette graph={graph} plugins={plugins} add={addBlock} addPlugin={addPluginBlock} open={paletteOpen}/></>;
}
function NodePalette({ graph, plugins, add, addPlugin, open }: { graph: FlowGraph; plugins: PluginCatalog; add: (kind: FlowNodeKind) => void; addPlugin: (plugin: PluginManifest, definition: PluginNodeDefinition) => void; open: boolean }) {
  const [search, setSearch] = useState("");
  const query = search.trim().toLowerCase();
  return <aside className={open ? "node-palette mobile-open" : "node-palette"}><div className="node-palette-head"><div><strong>Blocks</strong><span>Drag or click to add</span></div><label className="node-search"><Search size={14}/><input aria-label="Search blocks" placeholder="Filter blocks…" value={search} onChange={(event) => setSearch(event.target.value)}/></label></div><div className="node-palette-scroll">{catalog.map((group) => { const items = group.items.filter((kind) => !query || labels[kind].toLowerCase().includes(query)); return items.length ? <section key={group.category}><h3>{group.category}</h3>{items.map((kind) => { const disabled = kind === "input" && graph.nodes.some((node) => node.kind === "input"); const Icon = icons[kind]; return <button className={`palette-block tone-${nodeTone(kind)}`} key={kind} disabled={disabled} draggable={!disabled} onDragStart={(event) => { event.dataTransfer.setData("application/flowarr-node", kind); event.dataTransfer.effectAllowed = "move"; }} onClick={() => add(kind)}><Icon size={15}/><span><strong>{labels[kind]}</strong><small>{kind}</small></span><Plus size={13}/></button>; })}</section> : null; })}{plugins.plugins.map((plugin) => { const items = plugin.nodes.filter((item) => !query || `${item.label} ${item.description} ${plugin.name}`.toLowerCase().includes(query)); return items.length ? <section className="plugin-palette-group" key={plugin.id}><h3><Puzzle size={11}/>{plugin.name}<span>v{plugin.version}</span></h3>{items.map((definition) => <button className="palette-block tone-violet" key={definition.id} onClick={() => addPlugin(plugin, definition)} title={definition.description}><Puzzle size={15}/><span><strong>{definition.label}</strong><small>{definition.category ?? plugin.id}</small></span><Plus size={13}/></button>)}</section> : null; })}{plugins.errors.length > 0 && <div className="plugin-load-error"><CircleAlert size={14}/><span><strong>{plugins.errors.length} plugin {plugins.errors.length === 1 ? "error" : "errors"}</strong><small>{plugins.errors[0]?.error}</small></span></div>}</div></aside>;
}

const videoEncoders = [
  { group: "Software", options: [["copy", "Copy video"], ["libx264", "H.264 / x264"], ["libx265", "HEVC / x265"], ["libsvtav1", "AV1 / SVT-AV1"], ["libvpx-vp9", "VP9"]] },
  { group: "NVIDIA NVENC", options: [["h264_nvenc", "H.264 NVENC"], ["hevc_nvenc", "HEVC NVENC"], ["av1_nvenc", "AV1 NVENC"]] },
  { group: "Linux VAAPI", options: [["h264_vaapi", "H.264 VAAPI"], ["hevc_vaapi", "HEVC VAAPI"], ["av1_vaapi", "AV1 VAAPI"]] },
  { group: "Intel Quick Sync", options: [["h264_qsv", "H.264 QSV"], ["hevc_qsv", "HEVC QSV"], ["av1_qsv", "AV1 QSV"]] },
  { group: "AMD AMF", options: [["h264_amf", "H.264 AMF"], ["hevc_amf", "HEVC AMF"], ["av1_amf", "AV1 AMF"]] },
  { group: "Apple VideoToolbox", options: [["h264_videotoolbox", "H.264 VideoToolbox"], ["hevc_videotoolbox", "HEVC VideoToolbox"]] }
] as const;
const backend = (encoder: string) => encoder.endsWith("_nvenc") ? "nvenc" : encoder.endsWith("_vaapi") ? "vaapi" : encoder.endsWith("_qsv") ? "qsv" : encoder.endsWith("_amf") ? "amf" : encoder.endsWith("_videotoolbox") ? "videotoolbox" : "software";
const presetsFor = (encoder: string) => backend(encoder) === "nvenc" ? ["p1", "p3", "p5", "p7"] : backend(encoder) === "amf" ? ["speed", "balanced", "quality"] : backend(encoder) === "software" && encoder !== "copy" ? ["ultrafast", "fast", "medium", "slow", "slower"] : [];
const defaultPreset = (encoder: string) => backend(encoder) === "nvenc" ? "p5" : backend(encoder) === "amf" ? "balanced" : backend(encoder) === "software" && encoder !== "copy" ? "medium" : "";
const defaultDevice = (encoder: string) => backend(encoder) === "nvenc" ? "0" : backend(encoder) === "vaapi" || backend(encoder) === "qsv" ? "/dev/dri/renderD128" : "";

function defaultConfig(kind: FlowNodeKind): Record<string, unknown> | undefined {
  if (kind === "codec-check") return { codec: "h264" };
  if (kind === "bit-depth-check") return { bitDepth: 10 };
  if (kind === "hdr-check") return { hdr: true };
  if (kind === "resolution-check") return { minWidth: 3840, minHeight: 2160 };
  if (kind === "subflow") return { flowId: "" };
  if (kind === "plugin-node") return { pluginId: "", nodeType: "", options: {} };
  if (kind === "hevc-encode") return { crf: 24, preset: "medium" };
  if (kind === "video-encode") return { codec: "libx265", quality: 24, preset: "medium", device: "" };
  if (kind === "scale") return { width: 1920, height: 0 };
  if (kind === "pixel-format") return { pixelFormat: "yuv420p10le" };
  if (kind === "frame-rate") return { fps: 30 };
  if (kind === "crop") return { width: 1920, height: 1080, x: 0, y: 0 };
  if (kind === "rotate") return { rotation: "90cw" };
  if (kind === "deinterlace") return { mode: "yadif" };
  if (kind === "audio-encode") return { codec: "copy", bitrate: "192k" };
  if (kind === "audio-normalize") return { targetLufs: -16, truePeak: -1.5 };
  if (kind === "subtitle-mode") return { mode: "copy" };
  if (kind === "metadata-mode") return { mode: "copy" };
  if (kind === "custom-args") return { inputArgs: [], outputArgs: [] };
  if (kind === "custom-ffmpeg") return { args: ["-hide_banner", "-y", "-i", "{input}", "-map", "0", "-c:v", "libx265", "-crf", "24", "-c:a", "copy", "{output}"] };
  if (kind === "minimum-saving") return { percent: 10 };
  if (kind === "failure") return { message: "Media did not meet flow requirements" };
  return undefined;
}

function NodeConfigPanel({ node, flows, plugins, update, remove, close }: { node: FlowNode; flows: Summary[]; plugins: PluginManifest[]; update: (config: Record<string, unknown>) => void; remove: () => void; close: () => void }) {
  const config = node.config ?? {};
  const set = (key: string, value: unknown) => update({ ...config, [key]: value });
  const lines = (key: string) => Array.isArray(config[key]) ? (config[key] as unknown[]).filter((item): item is string => typeof item === "string").join("\n") : "";
  const selectedEncoder = String(config.codec ?? "libx265");
  const encoderBackend = backend(selectedEncoder);
  const encoderPresets = presetsFor(selectedEncoder);
  const plugin = plugins.find((item) => item.id === config.pluginId); const pluginNode = plugin?.nodes.find((item) => item.id === config.nodeType); const pluginOptions = config.options && typeof config.options === "object" && !Array.isArray(config.options) ? config.options as Record<string, unknown> : {};
  const setPluginOption = (key: string, value: unknown) => update({ ...config, options: { ...pluginOptions, [key]: value } });
  return <aside className="node-config"><header><div><Settings2 size={15}/><span><strong>{labels[node.kind]}</strong><small>{node.kind}</small></span></div><button className="icon" onClick={close} aria-label="Close block settings"><X size={16}/></button></header><div className="node-config-body">
    {node.kind === "codec-check" && <label>Expected codec<select value={String(config.codec ?? "h264")} onChange={(event) => set("codec", event.target.value)}><option value="h264">H.264</option><option value="hevc">HEVC</option><option value="av1">AV1</option><option value="vp9">VP9</option></select></label>}
    {node.kind === "bit-depth-check" && <label>Expected bit depth<select value={Number(config.bitDepth ?? 10)} onChange={(event) => set("bitDepth", Number(event.target.value))}><option value="8">8-bit</option><option value="10">10-bit</option><option value="12">12-bit</option></select></label>}
    {node.kind === "hdr-check" && <label>Expected range<select value={String(config.hdr ?? true)} onChange={(event) => set("hdr", event.target.value === "true")}><option value="true">HDR</option><option value="false">SDR</option></select></label>}
    {node.kind === "resolution-check" && <label>Minimum resolution<select value={`${config.minWidth ?? 3840}x${config.minHeight ?? 2160}`} onChange={(event) => { const [width, height] = event.target.value.split("x").map(Number); update({ ...config, minWidth: width, minHeight: height }); }}><option value="1280x720">720p</option><option value="1920x1080">1080p</option><option value="2560x1440">1440p</option><option value="3840x2160">4K</option><option value="7680x4320">8K</option></select></label>}
    {node.kind === "subflow" && <><label>Reusable flow<select aria-label="Referenced flow" value={String(config.flowId ?? "")} onChange={(event) => set("flowId", event.target.value)}><option value="" disabled>{flows.length ? "Choose a flow" : "No other flow available"}</option>{flows.map((flow) => <option key={flow.id} value={flow.id}>{flow.name} · rev {flow.revision}</option>)}</select><small>Its success block returns here. Failure and replace remain terminal.</small></label><div className="subflow-note"><Workflow size={15}/><span>Nested subflows supported. Circular references are rejected when saving.</span></div></>}
    {node.kind === "plugin-node" && pluginNode && <><div className="plugin-node-intro"><Puzzle size={15}/><span><strong>{plugin?.name}</strong><small>{pluginNode.description}</small></span></div>{(pluginNode.fields ?? []).map((field) => field.type === "select" ? <label key={field.key}>{field.label}<select value={String(pluginOptions[field.key] ?? field.default ?? "")} onChange={(event) => setPluginOption(field.key, event.target.value)}>{field.options?.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label> : field.type === "boolean" ? <label key={field.key}>{field.label}<select value={String(Boolean(pluginOptions[field.key] ?? field.default ?? false))} onChange={(event) => setPluginOption(field.key, event.target.value === "true")}><option value="true">Enabled</option><option value="false">Disabled</option></select></label> : <label key={field.key}>{field.label}<input type={field.type === "number" ? "number" : "text"} min={field.min} max={field.max} step={field.step} placeholder={field.placeholder} value={String(pluginOptions[field.key] ?? field.default ?? "")} onChange={(event) => setPluginOption(field.key, field.type === "number" ? Number(event.target.value) : event.target.value)}/></label>)}</>}
    {node.kind === "plugin-node" && !pluginNode && <div className="plugin-missing"><CircleAlert size={15}/>Plugin unavailable. Restore it or delete this block.</div>}
    {node.kind === "hevc-encode" && <><label>Video encoder<select value="libx265" disabled><option value="libx265">HEVC / x265 (software)</option></select></label><label>Quality (CRF)<input type="number" min="0" max="63" value={Number(config.crf ?? 24)} onChange={(event) => set("crf", Number(event.target.value))}/><small>Lower means higher quality.</small></label><label>Preset<select value={String(config.preset ?? "medium")} onChange={(event) => set("preset", event.target.value)}>{["ultrafast", "fast", "medium", "slow", "slower"].map((preset) => <option key={preset}>{preset}</option>)}</select></label></>}
    {node.kind === "video-encode" && <><label>Video encoder<select value={selectedEncoder} onChange={(event) => { const codec = event.target.value; update({ ...config, codec, preset: defaultPreset(codec), device: defaultDevice(codec) }); }}>{videoEncoders.map((group) => <optgroup label={group.group} key={group.group}>{group.options.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</optgroup>)}</select><small>The selected node must advertise this FFmpeg encoder.</small></label>{selectedEncoder !== "copy" && <label>Quality<input type="number" min="0" max="63" value={Number(config.quality ?? 24)} onChange={(event) => set("quality", Number(event.target.value))}/><small>Lower means higher quality. Flowarr maps this value to the encoder-specific FFmpeg option.</small></label>}{encoderPresets.length > 0 && <label>Preset<select value={String(config.preset || defaultPreset(selectedEncoder))} onChange={(event) => set("preset", event.target.value)}>{encoderPresets.map((preset) => <option key={preset}>{preset}</option>)}</select></label>}{encoderBackend === "nvenc" && <label>GPU index<input inputMode="numeric" value={String(config.device ?? "0")} onChange={(event) => set("device", event.target.value)} placeholder="0"/><small>Use 0, 1, 2… or <code>any</code>.</small></label>}{(encoderBackend === "vaapi" || encoderBackend === "qsv") && <label>Render device<input className="mono" value={String(config.device ?? "/dev/dri/renderD128")} onChange={(event) => set("device", event.target.value)} placeholder="/dev/dri/renderD128"/><small>Linux render device exposed to this node or container.</small></label>}{encoderBackend !== "software" && <div className="hardware-note">Hardware acceleration: {encoderBackend.toUpperCase()}. The job is assigned only to a node exposing {selectedEncoder}.</div>}</>}
    {node.kind === "scale" && <div className="field-pair"><label>Width<input type="number" min="0" value={Number(config.width ?? 1920)} onChange={(event) => set("width", Number(event.target.value))}/></label><label>Height<input type="number" min="0" value={Number(config.height ?? 0)} onChange={(event) => set("height", Number(event.target.value))}/><small>0 keeps aspect ratio.</small></label></div>}
    {node.kind === "pixel-format" && <label>Pixel format<select value={String(config.pixelFormat ?? "yuv420p10le")} onChange={(event) => set("pixelFormat", event.target.value)}><option value="yuv420p">8-bit 4:2:0</option><option value="yuv420p10le">10-bit 4:2:0</option><option value="yuv422p10le">10-bit 4:2:2</option><option value="yuv444p10le">10-bit 4:4:4</option></select></label>}
    {node.kind === "frame-rate" && <label>Output frame rate<select value={Number(config.fps ?? 30)} onChange={(event) => set("fps", Number(event.target.value))}><option value="23.976">23.976 fps</option><option value="24">24 fps</option><option value="25">25 fps</option><option value="30">30 fps</option><option value="50">50 fps</option><option value="60">60 fps</option></select><small>Frames are duplicated or dropped to match this rate.</small></label>}
    {node.kind === "crop" && <><div className="field-pair"><label>Width<input type="number" min="2" max="16384" value={Number(config.width ?? 1920)} onChange={(event) => set("width", Number(event.target.value))}/></label><label>Height<input type="number" min="2" max="16384" value={Number(config.height ?? 1080)} onChange={(event) => set("height", Number(event.target.value))}/></label></div><div className="field-pair"><label>Offset X<input type="number" min="0" value={Number(config.x ?? 0)} onChange={(event) => set("x", Number(event.target.value))}/></label><label>Offset Y<input type="number" min="0" value={Number(config.y ?? 0)} onChange={(event) => set("y", Number(event.target.value))}/></label></div></>}
    {node.kind === "rotate" && <label>Transform<select value={String(config.rotation ?? "90cw")} onChange={(event) => set("rotation", event.target.value)}><option value="90cw">90° clockwise</option><option value="90ccw">90° counter-clockwise</option><option value="180">180°</option><option value="hflip">Mirror horizontally</option><option value="vflip">Flip vertically</option></select></label>}
    {node.kind === "deinterlace" && <><div className="hardware-note">Uses FFmpeg YADIF to produce progressive frames. A video encoder is enabled automatically when needed.</div></>}
    {node.kind === "audio-encode" && <><label>Audio codec<select value={String(config.codec ?? "copy")} onChange={(event) => set("codec", event.target.value)}><option value="copy">Copy</option><option value="aac">AAC</option><option value="libopus">Opus</option><option value="ac3">AC3</option><option value="eac3">EAC3</option><option value="flac">FLAC</option><option value="none">Remove audio</option></select></label><label>Bitrate<input value={String(config.bitrate ?? "192k")} onChange={(event) => set("bitrate", event.target.value)} placeholder="192k"/></label></>}
    {node.kind === "audio-normalize" && <><label>Target loudness<input type="number" min="-70" max="-5" step=".5" value={Number(config.targetLufs ?? -16)} onChange={(event) => set("targetLufs", Number(event.target.value))}/><small>LUFS integrated. Streaming defaults are usually between -16 and -14.</small></label><label>True peak<input type="number" min="-9" max="0" step=".1" value={Number(config.truePeak ?? -1.5)} onChange={(event) => set("truePeak", Number(event.target.value))}/><small>dBTP ceiling. Audio is encoded to AAC automatically when needed.</small></label></>}
    {node.kind === "subtitle-mode" && <label>Subtitle streams<select value={String(config.mode ?? "copy")} onChange={(event) => set("mode", event.target.value)}><option value="copy">Copy all</option><option value="none">Remove all</option></select></label>}
    {node.kind === "metadata-mode" && <label>File metadata<select value={String(config.mode ?? "copy")} onChange={(event) => set("mode", event.target.value)}><option value="copy">Preserve metadata</option><option value="strip">Remove metadata and chapters</option></select><small>Stream data remains intact; strip removes container tags and chapters.</small></label>}
    {node.kind === "custom-args" && <><div className="advanced-warning">Advanced. Each line becomes one FFmpeg argument. No shell is used.</div><label>Input arguments<textarea rows={5} value={lines("inputArgs")} onChange={(event) => set("inputArgs", event.target.value.split("\n").filter(Boolean))} placeholder={"-hwaccel\nauto"}/><small>Inserted before <code>-i</code>.</small></label><label>Output arguments<textarea rows={7} value={lines("outputArgs")} onChange={(event) => set("outputArgs", event.target.value.split("\n").filter(Boolean))} placeholder={"-metadata\ntitle=My video"}/><small>Inserted before progress and output.</small></label></>}
    {node.kind === "custom-ffmpeg" && <><div className="advanced-warning">Replaces the complete builder command. Write one argument per line. Do not include <code>ffmpeg</code>. Required placeholders: <code>{"{input}"}</code> and <code>{"{output}"}</code>.</div><label>Complete FFmpeg arguments<textarea rows={18} value={lines("args")} onChange={(event) => set("args", event.target.value.split("\n").filter(Boolean))} spellCheck={false}/><small>Flowarr injects progress tracking before <code>{"{output}"}</code>.</small></label></>}
    {node.kind === "minimum-saving" && <label>Minimum saving<input type="number" min="0" max="100" value={Number(config.percent ?? 10)} onChange={(event) => set("percent", Number(event.target.value))}/><small>Percent. Output below threshold is rejected; original stays untouched.</small></label>}
    {node.kind === "failure" && <><div className="failure-note"><CircleX size={15}/>This terminal marks job failed without modifying original file.</div><label>Failure message<textarea rows={4} maxLength={500} value={String(config.message ?? "")} onChange={(event) => set("message", event.target.value)} placeholder="Why this media should not continue" required/></label></>}
    {!defaultConfig(node.kind) && <div className="no-config">This block has no settings.</div>}
  </div><footer className="node-config-footer"><button className="delete-block" onClick={remove}><Trash2 size={14}/>Delete block<kbd>Del</kbd></button></footer></aside>;
}
type FlowCanvasNode = Node<{ kind: FlowNodeKind; label: string; invalid: boolean }, "flow">;
function FlowNodeView({ data }: NodeProps<FlowCanvasNode>) {
  const branch = ["codec-check", "bit-depth-check", "hdr-check", "resolution-check"].includes(data.kind);
  const terminal = ["success", "replace", "failure"].includes(data.kind);
  const Icon = icons[data.kind];
  return <div className={`flow-node kind-${data.kind} tone-${nodeTone(data.kind)}${data.invalid ? " invalid" : ""}`}><Handle type="target" position={Position.Left}/><div className="node-icon"><Icon size={15}/></div><div><strong>{data.label}</strong><span>{data.kind}</span></div>{branch ? <><Handle id="true" type="source" position={Position.Right} style={{ top: "35%" }}/><Handle id="false" type="source" position={Position.Right} style={{ top: "70%" }}/></> : !terminal ? <Handle type="source" position={Position.Right}/> : null}</div>;
}

function nodeTone(kind: FlowNodeKind): "violet" | "cyan" | "orange" | "green" | "red" {
  if (["input", "probe-media", "subflow", "plugin-node"].includes(kind)) return "violet";
  if (["codec-check", "bit-depth-check", "hdr-check", "resolution-check", "minimum-saving"].includes(kind)) return "orange";
  if (["replace", "success"].includes(kind)) return "green";
  if (kind === "failure") return "red";
  return "cyan";
}
